name: action

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: self test action
        uses: ./
